app/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.post_detail,
        name="post_detail",
    ),
]

app/core/urls.py
from django.urls import path
from . import views
from .views import (
    property_for_sale,
    PropertyDetailView,
    book_property,
    AboutUsView,
)

app_name = "core"

urlpatterns = [
    path("", views.index, name="home"),
    path("property_for_sale/", views.property_for_sale, name="property_sale"),
    path("property/<int:pk>", PropertyDetailView.as_view(), name="property_detail"),
    path("contact/", views.contact, name="contact"),
    path("booking/", views.book_property, name="book_property"),
    path("about/", AboutUsView.as_view(), name="about_us"),
    path("search/", views.search, name="search"),
]

app/core/models.py
from django.db import models
from django.shortcuts import reverse


ROOM_CHOICES = (
    (1, "1"),
    (2, "2"),
    (3, "3"),
    (4, "4"),
    (5, "5"),
    (6, "6"),
    (7, "7"),
    (8, "8"),
)
BEDROOM_CHOICES = (
    (1, "1"),
    (2, "2"),
    (3, "3"),
    (4, "4"),
    (5, "5"),
    (6, "6"),
    (7, "7"),
    (8, "8"),
)
CATEGORY_CHOICES = (
    ("FR", "Featured"),
    ("RE", "Rent"),
)


class Agent(models.Model):
    name = models.CharField(max_length=100)
    occupation = models.CharField(max_length=100)
    photo = models.ImageField(blank=True, upload_to="Agents/%Y/%m/%d")
    description = models.TextField(blank=True)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Property(models.Model):
    title = models.CharField(max_length=100)
    agent = models.ForeignKey(Agent, on_delete=models.DO_NOTHING, null=True)
    area = models.FloatField()
    rooms = models.IntegerField(choices=ROOM_CHOICES, default=1, blank=True, null=True)
    bedroom = models.IntegerField(choices=BEDROOM_CHOICES, default=1)
    bathroom = models.IntegerField(default=1)
    garage = models.IntegerField(default=1)
    description = models.TextField()
    video_url = models.URLField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    location = models.CharField(max_length=50, default="MALINDI")
    listing_date = models.DateTimeField(auto_now_add=True)
    main_photo = models.ImageField(default="blackroq_3.jpg")
    photo_1 = models.ImageField(blank=True, upload_to="Property/%Y/%m/%d")
    photo_2 = models.ImageField(blank=True, upload_to="Property/%Y/%m/%d")
    photo_3 = models.ImageField(blank=True, upload_to="Property/%Y/%m/%d")
    photo_4 = models.ImageField(blank=True, upload_to="Property/%Y/%m/%d")
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=10, default="SL")
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Property"
        verbose_name_plural = "Properties"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:property_detail", kwargs={"pk": self.pk})


class Testimonial(models.Model):
    message = models.CharField(max_length=200)
    name = models.CharField(max_length=50)
    occupation = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class VideoTestimonial(models.Model):
    title = models.CharField(max_length=200)
    video_url = models.URLField()

    def __str__(self):
        return self.title


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return f"Message by {self.name}"


class Booking(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=12, blank=False)
    booking_date = models.DateTimeField()

    def __str__(self):
        return self.name


class About(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()

    def __str__(self):
        return self.title

app/core/forms.py
from django import forms
from .models import Contact, Booking


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ("name", "email", "message")
        widgets = {
            "name": forms.TextInput(attrs={"placeholder": "Name"}),
            "email": forms.TextInput(attrs={"placeeholder": "Email"}),
            "message": forms.Textarea(attrs={"placeholder": "Message..", "rows": 10}),
        }


class DateInput(forms.DateInput):
    input_type = "date"


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ("name", "email", "phone_number", "booking_date")
        widgets = {
            "name": forms.TextInput(attrs={"placeholder": "Name"}),
            "email": forms.TextInput(attrs={"placeholder": "Email"}),
            "phone_number": forms.NumberInput(),
            "booking_date": DateInput(),
        }

app/core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.db.models import Count, Q
from django.views.generic import DetailView, TemplateView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Property, Testimonial, Contact, About
from .forms import ContactForm, BookingForm
from blog.models import Post
from marketting.models import SignUp


class PropertyDetailView(DetailView):
    model = Property
    template_name = "core/property_details.html"


def index(request):
    properties = Property.objects.all()
    latest_sales = Property.objects.filter(category="FR").order_by("-listing_date")[:3]
    latest_posts = Post.objects.order_by("-publish")[:3]
    clients = Testimonial.objects.all()
    if request.method == "POST":
        email = request.POST["email"]
        new_signup = SignUp()
        new_signup.email = email
        new_signup.save()
        messages.info(request, "Thank you for subscribing")
        return redirect("core:home")

    context = {
        "properties": properties,
        "latest_sales": latest_sales,
        "clients": clients,
    }
    return render(request, "core/index.html", context)


def property_for_sale(request):
    sale = Property.objects.filter(category="SL")
    recommended = Property.objects.filter(category="SL").order_by("-listing_date")[:4]
    latest_posts = Post.objects.order_by("-publish")[:3]
    paginator = Paginator(sale, 8)
    page_request_variable = "page"
    page = request.GET.get(page_request_variable)
    try:
        paginated_queryset = paginator.page(page)
    except PageNotAnInteger:
        paginated_queryset = paginator.page(1)
    except EmptyPage:
        pagginated_queryset = paginator.page(paginator.num_pages)

    context = {
        "properties": paginated_queryset,
        "recommended": recommended,
        "latest_posts": latest_posts,
        "page_request_variable": page_request_variable,
    }
    return render(request, "core/property_for_sale.html", context)


def book_property(request):
    if request.method == "POST":
        form = BookingForm(request.POST)
        if form.is_valid():
            form.save()
            name = form.cleaned_data.get("name")
            messages.success(
                request,
                f"Thank you {name} for booking a viewing, we will get back to you.",
            )
            return redirect("core:home")
    else:
        form = BookingForm()

    context = {
        "form": form,
    }

    return render(request, "core/booking.html", context)


def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            name = form.cleaned_data.get("name")
            messages.success(
                request, f"Thank you {name} for contacting us, we will get back to you."
            )
            return redirect("core:home")
    else:
        form = ContactForm()

    context = {
        "form": form,
    }

    return render(request, "core/contact.html", context)


def is_valid_query(param):
    return param != "" and param is not None


def search(request):
    properties = Property.objects.all()
    query = request.GET.get("query")
    minimum_price = request.GET.get("minimum_price")
    maximum_price = request.GET.get("maximum_price")
    maximum_area = request.GET.get("maximum_area")
    minimum_area = request.GET.get("minimum_area")
    location = request.GET.get("location")

    if query:
        properties = properties.filter(Q(title__icontains=query)).distinct()
    if is_valid_query(minimum_price):
        properties = properties.filter(price__gte=minimum_price)
    if is_valid_query(maximum_price):
        properties = properties.filter(price__lte=maximum_price)
    if is_valid_query(minimum_area):
        properties = properties.filter(area__gte=minimum_area)
    if is_valid_query(maximum_area):
        properties = properties.filter(area__lte=maximum_area)
    if is_valid_query(location) and location != "Choose...":
        properties = properties.filter(Q(location__icontains=location))

    context = {
        "properties": properties,
    }
    return render(request, "core/search.html", context)


class AboutUsView(TemplateView):
    template_name = "core/about_us.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["about"] = About.objects.first()
        return context

app/core/templates/core/about_us.html
{% extends "core/base.html" %}
{% block content %}
{% include "core/header.html" %}
<div class="page-head">
    <div class="container">
        <div class="row">
            <div class="page-head-content">
                <h1 class="page-title">{{about.title}}</h1>
            </div>
        </div>
    </div>
</div>
<!-- End page header -->

<div class="content-area blog-page padding-top-40" style="background-color: #FCFCFC; padding-bottom: 55px;">
    <div class="container">
        <div class="row">
            <div class="blog-lst col-md-12 p0">
                <section id="id-100" class="post single">

                    <div id="post-content" class="post-body single wow fadeInLeft animated">
                        <p>
                            {{about.body|safe}}
                        </p>
                        <p>
                    </div>

                </section>
            </div>

        </div>

    </div>
</div>

{% include "core/footer.html" %}
{% endblock %}

app/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Real Estate</title>

    <!-- Bootstrap -->
    <link
        href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,wght@0,200;0,300;0,400;0,700;1,400&display=swap"
        rel="stylesheet">

    <link href="{% static 'core/lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/lib/animate.css' %}" rel="stylesheet">
    <link href="{% static 'core/lib/selectric/selectric.css' %}" rel="stylesheet">
    <link href="{% static 'core/lib/swiper/css/swiper.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/lib/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'core/lib/Magnific-Popup/magnific-popup.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/style.css' %}" rel="stylesheet">



</head>

<body class="page-load">

    {% if messages %}
    {% for message in messages%}
    <div class="alert alert-{{message.tags}}">
        {{message}}
    </div>

    {% endfor%}
    {% endif %}

    {% block content %}
    {% endblock content %}


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'core/lib/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'core/lib/popper.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'core/lib/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'core/lib/selectric/jquery.selectric.js' %}"></script>
    <script src="{% static 'core/lib/swiper/js/swiper.min.js' %}"></script>
    <script src="{% static 'core/lib/aos/aos.js' %}"></script>
    <script src="{% static 'core/lib/Magnific-Popup/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'core/lib/sticky-sidebar/ResizeSensor.min.js' %}"></script>
    <script src="{% static 'core/lib/sticky-sidebar/theia-sticky-sidebar.min.js' %}"></script>
    <script src="{% static 'core/lib/lib.js' %}"></script>
    <script>
        var swiper = new Swiper('.featured-slider', {
            slidesPerView: 2,
            centeredSlides: true,
            spaceBetween: 0,
            loop: true,
            autoplay: {
                delay: 5000,
                disableOnInteraction: false,
            },
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },
            breakpoints: {
                991: {
                    slidesPerView: 3,
                    centeredSlides: true,
                },
                768: {
                    slidesPerView: 2,
                    centeredSlides: true,
                },
                640: {
                    slidesPerView: 1,
                    centeredSlides: false,
                },
                320: {
                    slidesPerView: 1,
                    centeredSlides: false,
                }
            }
        });
    </script>

</body>

</html>

app/core/templates/core/booking.html
{% extends 'core/base.html'%}
{% load crispy_forms_tags %}
{% block content %}

<body>
    {% include 'core/header.html'%}
    <div class="page-head">
        <div class="container">
            <div class="row">
                <div class="page-head-content">
                    <h1 class="page-title">Book Viewing Date</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- End page header -->
    <!-- property area -->
    <div class="content-area recent-property padding-top-40" style="background-color: #FFF;">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="" id="contact1">
                        <!-- /.row -->
                        <h2>Book Viewing</h2>
                        <form method="POST" action=".">
                            {%csrf_token %}
                            <div class="row">
                                <div class="col-sm-12">
                                    {{form.name|as_crispy_field}}
                                </div>
                                <div class="col-sm-12">
                                    {{form.email|as_crispy_field}}
                                </div>
                                <div class="col-sm-12">
                                    {{form.phone_number|as_crispy_field}}
                                </div>
                                <div class="col-sm-12 col-md-4">
                                    {{form.booking_date|as_crispy_field}}
                                </div>
                                <div class="col-sm-12 text-center">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-envelope-o"></i> Book
                                        Viewing</button>
                                </div>
                            </div>
                            <!-- /.row -->
                        </form>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer area-->
    {% include 'core/footer.html'%}
</body>
{% endblock %}

app/core/templates/core/contact.html
{% extends 'core/base.html'%}

{% load crispy_forms_tags %}
{% block content %}

<body>
    {% include 'core/header.html'%}
    <div class="page-head">
        <div class="container">
            <div class="row">
                <div class="page-head-content">
                    <h1 class="page-title">Contact Us</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- End page header -->
    <!-- property area -->
    <div class="content-area recent-property padding-top-40" style="background-color: #FFF;">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="" id="contact1">
                        <!-- /.row -->
                        <h2>Contact form</h2>
                        <form method="POST" action=".">
                            {%csrf_token %}
                            <div class="row">
                                <div class="col-sm-12">
                                    {{form.name|as_crispy_field}}
                                </div>
                                <div class="col-sm-12">
                                    {{form.email|as_crispy_field}}
                                </div>
                                <div class="col-sm-12">
                                    {{form.message|as_crispy_field}}
                                </div>
                                <div class="col-sm-12 text-center">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-envelope-o"></i> Send
                                        message</button>
                                </div>
                            </div>
                            <!-- /.row -->
                        </form>
                    </div>
                    <hr>
                    <div class="row mt-10">
                        <div class="col-sm-4">
                            <h3><i class="fa fa-map-marker"></i> Address</h3>
                            <p>13/25 Upperhill
                                <br>Nairobi
                                <strong>Kenya</strong>
                            </p>
                        </div>
                        <!-- /.col-sm-4 -->
                        <div class="col-sm-4">
                            <h3><i class="fa fa-phone"></i> Call center</h3>
                            <p><strong>+254 555 444 333</strong></p>
                        </div>
                        <!-- /.col-sm-4 -->
                        <div class="col-sm-4">
                            <h3><i class="fa fa-envelope"></i> Emails</h3>
                            <ul>
                                <li><strong><a href="mailto:">info@blackroq.co.ke</a></strong> </li>

                            </ul>
                        </div>
                        <!-- /.col-sm-4 -->
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer area-->
    {% include 'core/footer.html'%}

</body>
{% endblock %}

app/core/templates/core/footer.html
{% load static %}
<!-- Footer Section Start -->
<footer id="footer" class="bg-light footer-light">
  <div class="container container-1000">
    <div class="row">
      <div class="col-lg-3">
        <!-- <p><span class="icon-uilove icon-uilove-realestate"></span></p> -->
        <img class="logo" src="{% static "core/img/icons/new_way-bg.png"%} " alt="logo">
        <address class="mb-3">
          <strong>New Way Developers.</strong><br>
          Nairobi CBD<br>
          Kenya<br>
          <abbr title="Phone">P:</abbr> (+254) 726 610840
        </address>
        <div class="footer-social mb-4"><a href="#" class="ml-2 mr-2"><span class="fa fa-twitter"></span></a> <a
            href="#" class="ml-2 mr-2"><span class="fa fa-facebook"></span></a> <a href="#" class="ml-2 mr-2"><span
              class="fa fa-instagram"></span></a></div>
      </div>
      <div class="col-lg-2 col-sm-4">
        <div class="footer-links">
          <ul class="list-unstyled">
            <li class="list-title"><a href="#">About</a></li>
            <li><a href="#">Company</a></li>
            <li><a href="#">Community</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-2 col-sm-4">
        <div class="footer-links">
          <ul class="list-unstyled">
            <li class="list-title"><a href="#">Links</a></li>
            <li><a href="#">For Rent</a></li>
            <li><a href="#">Land</a></li>
            <li><a href="#">Agents</a></li>
            <li><a href="#">Property Guides</a></li>
            <li><a href="#">Jobs</a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-2 col-sm-4">
        <div class="footer-links">
          <ul class="list-unstyled">
            <li class="list-title"><a href="#">Help</a></li>
            <li><a href="#">Book Property</a></li>
            <li><a href="#">FAQ</a></li>

          </ul>
        </div>
      </div>
      <div class="col-lg-3">
        <div class="text-lg-right ml-lg-2">
          <form>
            <div class="list-title">Subscribe</div>
            <div class="input-group input-group-lg">
              <input type="text" name="email" class="form-control form-control-lg subscribe-input" placeholder="Email">
              <div class="input-group-append ml-0">
                <button class="btn subscribe-button" type="button"><i class="fa fa-envelope"></i></button>
              </div>
            </div>
          </form>
        </div>
      </div>

    </div>
    <div class="footer-credits d-lg-flex justify-content-lg-between align-items-center">
      <div>Powered by <strong>newwaydevelopers</strong></div>

      <div>© 2020 newwaydevelopers. All Rights Reserved</div>
    </div>
  </div>
</footer>
<!-- Footer Section End -->

app/core/templates/core/property_for_sale.html
{% extends "core/base.html"%}

{% block content %}

<body>
    {% include "core/header.html" %}

    <div class="page-head">
        <div class="container">
            <div class="row">
                <div class="page-head-content">
                    <h1 class="page-title">Properties for Sale in Kenya</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- End page header -->

    <!-- property area -->
    <div class="properties-area recent-property" style="background-color: #FFF;">
        <div class="container">
            <div class="row">


                <div class=" col-md-9 pr0 padding-top-40 properties-page">

                    <div class="col-md-12 clear">
                        <div id="list-type" class="proerty-th">
                            {% for property in properties %}
                            <div class="col-sm-6 col-md-4 p0">

                                <div class=" box-two proerty-item">
                                    <div class="item-thumb">
                                        <a href="{{property.get_absolute_url}}"><img
                                                src="{{property.main_photo.url}}"></a>
                                    </div>

                                    <div class="item-entry overflow">
                                        <h5><a href="{{property.get_absolute_url}}">{{property.title}}
                                            </a></h5>
                                        <div class="dot-hr"></div>
                                        <h4 class="s-property-title">{{property.get_location_display}}
                                        </h4>
                                        <span class="pull-left"><b> Area :</b>
                                            {{property.area}} sqm </span>
                                        <span class="proerty-price pull-right"> Ksh
                                            {{property.price}}</span>
                                        <p style="display: none;">Suspendisse ultricies
                                            Suspendisse ultricies Nulla quis
                                            dapibus nisl. Suspendisse ultricies commodo arcu
                                            nec pretium ...</p>

                                    </div>
                                </div>

                            </div>
                            {% endfor %}
                        </div>
                    </div>

                    <div class=" col-md-12">
                        <div class="pull-right">
                            <div class="pagination">
                                <ul>
                                    {% if properties.has_previous%}
                                    <li><a
                                            href="?{{page_request_variable}}={{properties.previous_page_number}}">Prev</a>
                                    </li>
                                    {% endif %}
                                    <li><a href="">{{properties.number}}</a></li>

                                    {% if properties.has_next %}
                                    <li><a href="?{{page_request_variable}}={{properties.next_page_number}}">Next</a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                {% include "core/sidebar.html" with latest_posts=latest_posts %}
            </div>
        </div>
    </div>

    <!-- Footer area-->
    {% include "core/footer.html" %}

</body>

{% endblock content %}

app/core/templates/core/sidebar.html
<div class="col-md-3 p0 padding-top-40">
    <div class="blog-asside-right pr0">
        <div class="panel panel-default sidebar-menu wow fadeInRight animated">
            <div class="panel-heading">
                <h3 class="panel-title">Smart search</h3>
            </div>
            <div class="panel-body search-widget">
                <form method="GET" action="{% url 'core:search' %}">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-12 col-lg-12">
                            <label for="minimum_view_count">Keywords</label>
                            <input type="text" class="form-control" name="query" placeholder="Keywords">

                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6 col-lg-6">
                            <label for="minimum_view_count">Min Price</label>
                            <input type="number" min="0" class="form-control" name="minimum_price" placeholder="0">
                        </div>
                        <div class="form-group col-md-6 col-lg-6">
                            <label for="maximum_view_count">Maxi Price</label>
                            <input type="number" min="0" class="form-control" name="maximum_price" placeholder="10000">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6 col-lg-6">
                            <label for="minimum_area">Min Area</label>
                            <input type="number" class="form-control" name="minimum_area" placeholder="Area">
                        </div>
                        <div class="form-group col-md-6 col-lg-6">
                            <label for="maximum_area">Max Area</label>
                            <input type="number" class="form-control" name="maximum_area" placeholder="Area">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12 col-lg-12">
                            <label for="inputState">Location</label>
                            <select id="inputState" name="location" class="form-control">
                                <option selected>Choose...</option>
                                {% for property in properties%}
                                <option value="{{property.location}}">{{property.location}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Search</button>
                </form>
            </div>
        </div>

        <div class="panel panel-default sidebar-menu wow fadeInRight animated">
            <div class="panel-heading">
                <h3 class="panel-title">Latest Articles</h3>
            </div>
            <div class="panel-body recent-property-widget">
                <ul>
                    {% for post in latest_posts %}
                    <li>
                        <div class="col-md-3 col-sm-3 col-xs-3 blg-thumb p0">
                            <a href="{{post.get_absolute_url}}"><img src="{{post.thumbnail.url}}"></a>
                        </div>
                        <div class="col-md-8 col-sm-8 col-xs-8 blg-entry">
                            <h6> <a href="single.html">{{post.name}}</a></h6>
                            <span class="property-price">By {{post.author}}</span>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>